### ISSUE TITLE
Fail during SSR

### ISSUE THREAD

**Issue by oleh-nb** [medici-collective/puzzle-sdk#33]
I am using `import * as puzzle from "@puzzlehq/sdk-core"` in an ssr environment. It fails with this error:

```
ReferenceError: navigator is not defined
    at gb (file:///var/task/vercel/path0/node_modules/.pnpm/@puzzlehq+sdk-core@0.2.32_buffer@6.0.3_react@18.3.0/node_modules/@puzzlehq/sdk-core/dist/index-BTk6HIJS.js:8635:26)
    at file:///var/task/vercel/path0/node_modules/.pnpm/@puzzlehq+sdk-core@0.2.32_buffer@6.0.3_react@18.3.0/node_modules/@puzzlehq/sdk-core/dist/index-BTk6HIJS.js:8676:9
```

Version that does NOT work: 0.2.32

However, version 0.2.18 works OK.

And, please, don't bundle and minify the source code when you are publishing to npm. It's impossible to debug. (use `tsc` instead)

**Comment by jonandgon** [comment]
Hey @oleh-nb, I just published `@puzzlehq/sdk-0.3.2-beta.7`. Can you give that a try and let me know if that helps?

We are using `pnpm patch` to make necessary WalletConnect fixes, and this requires using a bundler (we are using Vite). But I understand your frustration. I have disabled minification in the meantime. 

We can look into actually forking the WalletConnect SDKs, which should help. But this is a lower priority as we are gearing up for mainnet.
